#version 460 core
layout(local_size_x=128) in;
#import <voxy:lod/section.glsl>
#import <voxy:lod/gl46/bindings.glsl>
layout(std430,binding=0) readonly buffer Commands { DrawCommand source[]; };
layout(std430,binding=1) buffer Counts { uint counts[]; };
layout(std430,binding=2) writeonly buffer Output { DrawCommand outputCommands[]; };
layout(std430,binding=3) readonly buffer Sections { SectionMeta sections[]; };
layout(std430,binding=4) readonly buffer Lookup { uint sectionCount; uint lookup[]; };
void main() {
    uint stride = gl_NumWorkGroups.x*128u;
    for (uint i=gl_GlobalInvocationID.x;i<counts[3];i+=stride) {
        DrawCommand command = source[i];
        SectionMeta section = sections[lookup[command.baseInstance]];
        uint flags = section.a.z;
        // Keep meshes without flags.
        if ((flags & 0x80000000u) != 0u && (flags & 0x40000000u) == 0u) continue;
        uint dst = atomicAdd(counts[11],1u);
        outputCommands[dst] = command;
    }
}
